server:
  port: 9090

# Connection url for the database "Local MySQL"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/G56_TODO_DB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Berlin
    username: root
    password: 1234

    tomcat:
      initial-size: 15
      max-wait: 20000
      max-active: 50
      max-idle: 15
      min-idle: 8
      default-auto-commit: true
      test-while-idle: true
      validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
